/**
 * configuration.js
 * ~ just to help kitchen manage config.json
 * ~ and help website app manage config.site.data
 */
function configuration(){
this.version='1.0.0';
this.Force=null;
/* kitchen */
this.kitchen=function(plug){
  this.Force=plug.Force;
  if(ForceWebsite.query.hasOwnProperty('page')){
    if(ForceWebsite.query.page=='config'){
      return this.kitchenConfig(plug);
    }
  }
  var p='',
  _this=this,
  nconfig=ForceWebsite.buildElement('button',null,{
    'class':'button button-pink',
  },[
    ForceWebsite.buildElement('i',null,{
      'class':'fa fa-edit',
    }),
    document.createTextNode('Edit Config'),
  ]),
  nback=ForceWebsite.buildElement('button',null,{
    'class':'button button-blue',
  },[
    ForceWebsite.buildElement('i',null,{
      'class':'fa fa-arrow-left',
    }),
    document.createTextNode('Back'),
  ]),
  nkdp=ForceWebsite.buildElement('div',null,{
    'class':'configuration-buttons',
  },[
    nback,nconfig,
  ]);
  nback.onclick=function(e){
    ForceWebsite.go(ForceWebsite.kkey+'=dashboard');
  };
  nconfig.onclick=function(e){
    ForceWebsite.go(ForceWebsite.kkey
      +'=plug&ns=configuration&page=config');
  };
  nkdp.appendTo(ForceWebsite.body);
  
  var nform=ForceWebsite.buildElement('form'),
  ndp=ForceWebsite.buildElement('div',null,{
    'class':'configuration-data',
  },[
    
  ]);
  nform.appendTo(ForceWebsite.body);
  nform.onsubmit=function(e){
    e.preventDefault();
    var formdata={},
    nsave=e.submitter;
    for(var p of e.target){
      p.disabled=true;
      if(p.name){
        if(!formdata.hasOwnProperty(p.dataset.key)){
          formdata[p.dataset.key]={};
        }
        var pval=p.value;
        if(p.value.match(/^\d+(\.\d+)?$/)){
          pval=parseFloat(p.value);
        }else if(p.value=='true'){
          pval=true;
        }else if(p.value=='false'){
          pval=false;
        }
        formdata[p.dataset.key][p.dataset.name]=_this.parse(pval);
      }
    }
    _this.data=formdata;
    nsave.value='Saving...';
    ForceWebsite.request('config.put',function(r){
      for(var p of e.target){
        p.disabled=false;
      }
      nsave.value='Save';
      if(r.trim().match(/^error/i)){
        return _this.Force.splash(r);
      }
      _this.Force.splash('Saved.');
    },{
      content:JSON.stringify(_this.data),
    });
    return false;
  };
  ndp.appendTo(nform);
  ForceWebsite.fetch('config.fetch',function(r){
    _this.data=r;
    var nrow=ForceWebsite.buildElement('div',null,{
      'class':'configuration-row',
    },[
      ForceWebsite.buildElement('h1','Configuration [site.data]'),
    ]);
    nrow.appendTo(ndp);
    for(var o in r){
      var p=r[o],
      d=_this.table();
      d.addRowSingle(o);
      for(var i in p){
        var purse=_this.purse(p[i]),
        itag=p[i]===purse?'input':'textarea',
        irow=ForceWebsite.buildElement(itag,null,{
          'class':'kitchen-input-title',
          'name':i+'['+o+']',
          'data-key':o,
          'data-name':i,
          'value':''+purse,
        },null,null,p[i]!==purse?purse:null);
        d.addRowElement(i,irow);
      }
      var nrow=ForceWebsite.buildElement('div',null,{
        'class':'configuration-row',
      },[d]);
      nrow.appendTo(ndp);
    }
    var nsave=ForceWebsite.buildElement('input',null,{
      'class':'save',
      'type':'submit',
      'value':'Save',
      'data-after':'Save',
      'data-before':'Saving...',
    }),
    nrow=ForceWebsite.buildElement('div',null,{
        'class':'configuration-row',
    },[nsave]);
    nrow.appendTo(ndp);
  });
};
/* kitchen config */
this.kitchenConfig=async function(plug){
  await this.Force.alert("Please be careful!\nDo not edit this file if you don't understand JSON syntax!");
  var p='',
  _this=this,
  ntitle=ForceWebsite.buildElement('input',null,{
    'class':'kitchen-input-title',
    'value':'config.json',
    'readonly':'readonly',
  }),
  ncontent=ForceWebsite.buildElement('textarea',null,{
    'class':'kitchen-input-content configuration-textarea',
    'placeholder':'Loading...',
  }),
  nsave=ForceWebsite.buildElement('input',null,{
    'class':'save',
    'type':'submit',
    'value':'Save',
    'data-after':'Save',
    'data-before':'Saving...',
  }),
  nback=ForceWebsite.buildElement('button',null,{
    'class':'button button-blue',
  },[
    ForceWebsite.buildElement('i',null,{
      'class':'fa fa-arrow-left',
    }),
    document.createTextNode('Back'),
  ]),
  ndp=ForceWebsite.buildElement('div',null,{
    'class':'configuration-buttons',
  },[
    ntitle,ncontent,nback,nsave,
  ]);
  nback.onclick=function(e){
    ForceWebsite.go(ForceWebsite.kkey+'=plug&ns=configuration');
  };
  nsave.onclick=function(e){
    ncontent.disabled=true;
    nback.disabled=true;
    nsave.disabled=true;
    nsave.value='Saving...';
    ForceWebsite.request('config.put',function(r){
      ncontent.disabled=false;
      nback.disabled=false;
      nsave.disabled=false;
      nsave.value='Save';
      if(r.trim().match(/^error/i)){
        return _this.Force.splash(r);
      }
      _this.Force.splash('Saved.');
    },{
      content:ncontent.value,
    });
  };
  ndp.appendTo(ForceWebsite.body);
  ForceWebsite.fetch('config.get',function(r){
    ncontent.value=r;
  });
};
/* purse */
this.purse=function(v){
  if(v===null
    ||typeof v==='boolean'
    ||typeof v==='string'
    ||typeof v==='number'){
      return v;
    }
  return JSON.stringify(v);
};
/* parse */
this.parse=function(v){
  var r=null;
  try{
    r=JSON.parse(v);
  }catch(e){
    return v;
  }return r?r:v;
};
/* table */
this.table=function(){
  var tbody=ForceWebsite.buildElement('tbody'),
  thead=ForceWebsite.buildElement('thead'),
  table=ForceWebsite.buildElement('table',null,{
    'class':'configuration-table',
    'cellpadding':'0px',
    'cellspacing':'0px',
    'border':'0px',
  },[thead,tbody]);
  table.body=tbody;
  table.head=thead;
  table.addRow=function(key,value){
    var td1=ForceWebsite.buildElement('td',key),
    td2=ForceWebsite.buildElement('td',value),
    trow=ForceWebsite.buildElement('tr',null,{},[td1,td2]);
    trow.appendTo(this.body);
    return this;
  };
  table.addRowElement=function(key,value){
    var td1=ForceWebsite.buildElement('td',key),
    td2=ForceWebsite.buildElement('td',null,{},[value]),
    trow=ForceWebsite.buildElement('tr',null,{},[td1,td2]);
    trow.appendTo(this.body);
    return this;
  };
  table.addRowSingle=function(key){
    var td1=ForceWebsite.buildElement('td',key,{
      'class':'colspan',
      'colspan':'2'
    }),
    trow=ForceWebsite.buildElement('tr',null,{},[td1]);
    trow.appendTo(this.body);
    return this;
  };
  return table;
};
}


